// <auto-generated />
using System;
using AzeWHV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzeWHV.Data.Migrations
{
    [DbContext(typeof(AzeDataContext))]
    partial class AzeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzeWHV.Data.CustomInfo", b =>
                {
                    b.Property<Guid>("CustomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressSuburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeenToNZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("Birthday")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IdEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("IdStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NzVisitTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PassportExpireDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomId");

                    b.ToTable("CustomInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
